name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to PyCraft! It seems like this is your first time contributing. Be sure to read the contribution guidelines!"
        pr-message: "Welcome to PyCraft! It seems like this is your first time contributing. Be sure to read the contribution guidelines!"
